sensor: !include sensors.yaml
automation: !include automations.yaml


switch:
  - platform: template
    switches:
      vp_status_switch:
        value_template: "{{ is_state('switch.shelly_shsw_1_34945470be74', 'off') }}"
        turn_on:
          service: switch.turn_off
          entity_id: switch.shelly_shsw_1_34945470be74
        turn_off:
          service: switch.turn_on
          entity_id: switch.shelly_shsw_1_34945470be74
